### ISSUE TITLE
功能请求！可以增加这个简单的构图功能吗

### ISSUE THREAD

**Issue by hahajaja** [huchenlei/ComfyUI_densediffusion#8]
![image](https://github.com/huchenlei/ComfyUI_densediffusion/assets/23209894/dbfb7f9a-1ac7-4f53-82be-9f7e87483d89)

代码来源 https://github.com/Davemane42/ComfyUI_Dave_CustomNode

**Comment by huchenlei** [comment]
See https://github.com/huchenlei/ComfyUI_omost
![338019384-bff0f6d5-ea28-41b2-ae7c-fec29691584f](https://github.com/huchenlei/ComfyUI_densediffusion/assets/20929282/2984ad64-fcea-4fb0-a17d-188ee8374505)
![338019393-eb2a692f-3643-434a-a1d9-4443c82629b8](https://github.com/huchenlei/ComfyUI_densediffusion/assets/20929282/af582beb-b4de-4cf7-bb10-80cc45c5096c)
